server:
  port: 9191

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: MATERIAL-SERVICE
          uri: lb://MATERIAL-SERVICE
          predicates:
            - Path=/api/v1/materials/**


eureka:
  client:
    registry-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost